CP/Controllers/CorporateContactsController.cs
using CP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EquiModels;
using System.IO;
using System.Configuration;



namespace CP.Controllers
{
    [Authorize]
    public class CorporateContactsController : Controller
    {
        // GET: CorporateContacts
        public ActionResult Index(string Status = "1")
        {
            ViewBag.Search = Status;
            return View();
        }

        public ActionResult Add()
        {
            try
            {
                TempData["Actionname"] = "Add";
                CorporateContactViewModel viewModel = new CorporateContactViewModel();
                ViewBag.CompanyList = new SelectList(CompaniesRepository.GetAll("1", null), "Id", "Name");
                ViewBag.Errors = null;
                return PartialView(viewModel);
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }
        [HttpPost]
        public ActionResult Add(CorporateContactViewModel viewModel)
        {
            try
            {
                TempData["Actionname"] = "Add";
                ViewBag.CompanyList = new SelectList(CompaniesRepository.GetAll("1", null), "Id", "Name");

                CorporateContactsRepository.Add(viewModel, "CorporateContacts/Add");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView(viewModel);
                }
                else
                {
                    TempData["message"] = CommonRepository.StatusMessage;
                    return RedirectToAction("Add");
                }
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                var response = CorporateContactsRepository.Get(Id);
                ViewBag.CompanyList = new SelectList(CompaniesRepository.GetAll("1", null), "Id", "Name");
                ViewBag.Errors = null;
                return PartialView("Add", response);
            }
            catch (Exception e)
            {
                return View("Error", e);
            }

        }

        [HttpPost]
        public ActionResult Edit(CorporateContactViewModel viewModel)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                ViewBag.CompanyList = new SelectList(CompaniesRepository.GetAll("1", null), "Id", "Name");
                CorporateContactsRepository.Add(viewModel, "CorporateContacts/Edit");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView("Add", viewModel);
                }
                TempData["message"] = CommonRepository.StatusMessage;
                return RedirectToAction("Edit", new { viewModel.Id });
            }
            catch (Exception e)
            {
                return View("Error", e);
            }

        }

        public ActionResult DeleteOrRestore(int Id, string Mode)
        {
            try
            {
                string Path = null;
                if (Mode == "Delete")
                { Path = "CorporateContacts/Delete"; }
                else Path = "CorporateContacts/Restore";
                CorporateContactsRepository.DeleteOrRestore(Id, Path);
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                }
                TempData["message"] = CommonRepository.StatusMessage;
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error", e);
            }

        }

        [HttpGet]
        public JsonResult GetAll(string Status)
        {
            var data = CorporateContactsRepository.GetAll(Status);
            return Json(data, JsonRequestBehavior.AllowGet);
        }


    }
}

CP/Views/CorporateContacts/Add.cshtml
@model EquiModels.CorporateContactViewModel
@{string actionname = TempData["Actionname"].ToString();}


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close btn-lg" onclick="javascript: location.reload();">
            &times;
        </button>
        @if (actionname == "Add")
        {
            <h4 class="modal-title" id="name">
                Add Corporate Contact
            </h4>
        }
        else
        {
            <h4 class="modal-title" id="name">@("Edit " + Model.Name)</h4>
        }
    </div>
    <div class="modal-body" style="height: 500px; overflow-y: scroll;">
        <img src="@Url.Content("~/Content/Images/loader.gif")" id="loading" class="loadingImg" height="90px" width="90px" />
        <div>
            <span style="color: red;"><em>* Indicates required field</em></span>
            <br />
            <div id="errormessage">
                <ul>
                    @if (ViewBag.Errors != null)
                    {
                        foreach (var err in ViewBag.Errors)
                        {
                            <li>@err.Value</li>
                        }
                    }

                </ul>
            </div>
            @if (TempData["message"] != null && TempData["message"].ToString().Length > 0)
            {
                <div id="message">
                    @TempData["message"]
                </div>
            }
            @using (Html.BeginForm(actionname, "CorporateContacts", FormMethod.Post, new { enctype = "multipart/form-data", @onsubmit = "return OnFormSubmit(this);" }))
            {
                @Html.HiddenFor(x => x.Id)
                @Html.HiddenFor(x => x.Name)
                @Html.HiddenFor(x => x.Sector)
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-xs-2 required">
                                        <label> First Name</label><span style="color: red; font-size: 17px;">*</span>
                                    </div>
                                    <div class="col-xs-4">
                                        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", @maxlength = "255" })
                                    </div>
                                    <div class="col-xs-2">
                                        <label>Last Name</label>
                                    </div>
                                    <div class="col-xs-4">
                                        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", @maxlength = "255" })

                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-xs-2 required">
                                        <label> Company</label><span style="color: red; font-size: 17px;">*</span>
                                    </div>
                                    <div class="col-xs-4">
                                        @Html.DropDownListFor(x => x.CompanyId, ViewBag.CompanyList as SelectList, "Select Company", new { @class = "form-control demo-cs-multiselect" })
                                    </div>
                                    <div class="col-xs-2">
                                        <label>Designation</label>
                                    </div>
                                    <div class="col-xs-4">

                                        @Html.TextBoxFor(x => x.Designation, new { @class = "form-control", @maxlength = "255" })

                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-xs-2">
                                        <label> Phone</label>
                                    </div>
                                    <div class="col-xs-4 ">
                                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", type = "tel", @maxlength = "50" })

                                    </div>

                                    <div class="col-xs-2 required">
                                        <label>Email</label><span style="color: red; font-size: 17px;">*</span>
                                    </div>
                                    <div class="col-xs-4">
                                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @maxlength = "255" })

                                    </div>

                                </div>

                                <br />

                                <div class="row">
                                    <div class="col-xs-2">
                                        <label>Mobile</label>
                                    </div>
                                    <div class="col-xs-4 ">
                                        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control cellno", @maxlength = "15", onKeyDown = "doCheck(this)" })

                                    </div>

                                    <div class="col-xs-2 ">
                                        <label>Fax</label>
                                    </div>
                                    <div class="col-xs-4">
                                        @Html.TextBoxFor(x => x.Fax, new { @class = "form-control", @maxlength = "255" })

                                    </div>

                                </div>
                                <br />
                                @if (actionname == "Edit")
                                {
                                    <div class="row">
                                        <div class="col-xs-2">
                                            <label>Sector</label>
                                        </div>
                                        <div class="col-xs-4 ">
                                            @Html.DisplayTextFor(x => x.Sector)

                                        </div>

                                    </div>


                                    <br />
                                }
                                    <div class="row">
                                        <div class="col-xs-4">
                                            <input type="submit" class="btn btn-info" value="Save" id="save">
                                            <input type="button" class="btn btn-warning" value="Cancel" onclick="javascript: location.reload();">
                                        </div>
                                    </div>

                                </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $(".cellno").intlTelInput(
            {
                utilsScript: "Scripts/utils.js"
            });
        LoadDropDown();
        LoadPhone($('.cellno').val());
    });

    function doCheck(CurrentTextBox) {
        var keycode;
        var len;
        keycode = (event.which) ? event.which : event.keyCode;
        className = "country highlight";
        var data = document.getElementsByClassName(className)[0];

        if (typeof data === "undefined") {
            className = "country active";
            data = document.getElementsByClassName(className)[0];
            if (typeof data === "undefined") {
                className = "country preferred";
            }
        }
        len = document.getElementsByClassName(className)[0].lastChild.textContent.length;
        if (GetCursorLocation(CurrentTextBox) <= len - 1) {
            event.returnValue = false;
        }
        else if ((GetCursorLocation(CurrentTextBox) == len) && (keycode == 8)) {
            event.returnValue = false;
        }
        else {
            event.returnValue = true;
        }
    }

    @*$(function () {

        debugger
        var jsonMobile = '@Html.Raw(Json.Encode(Model.Mobile))';
        
           var Mobile = JSON.parse(jsonMobile);
           console.log(Mobile);
       
        if (Mobile != null) {
            validateMobile(Mobile, "Mobile");
        }
        else
        { $('.cellno').val("+91"); }

     });*@





    //function validateMobile(number, id) {
    //    var filter = /^\+(?:[0-9] ?){9,14}[0-9]$/;
    //    debugger;
    //    if (filter.test(number) && number.toString().length <= 4)
    //    {
    //        return true;
    //    }
    //    else {
    //        $("#" + id).removeClass("input-validation-error");
    //        $("#" + id).css("border-color", "red");
    //        $("#" + id).tooltip('destroy');
    //    }
    //}


    function OnFormSubmit(frm) {
        var res = ' @TempData["message"]';
        SubmitForm(frm,res);
        return false;
    }

    $("#Mobile").removeClass("input-validation-error");
    $("#Mobile").css("border", "1px solid #ccc");
    $("#Mobile").tooltip('destroy');


</script>

CP/Views/CorporateContacts/Index.cshtml
@model EquiModels.CorporateContactViewModel
@{
    ViewBag.Title = "Corporate Contacts";

}

<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Corporate Contacts</h3>
            </div>

            @if (TempData["message"] != null && TempData["message"].ToString().Length > 0)
            {
                <div id="message" style="position:absolute;width:80%;top:58px;left:100px;">
                    @TempData["message"]
                </div>
            }
            <br />
            <div class="panel-body">
                <div class="panel-control">
                    <div class="btn-group" style="float:left;margin-top:19px;">

                        <a class="btn btn-default" id="DeleteItemsBtn" href="javascript:void(0);" onclick="ShowDeletedRecords('CorporateContacts', 'GetAll','DeletedItems', '#CorporateContacts','AddModel_');">Deleted Items</a>
                        <a class="btn btn-default" href="javascript:void(0);"data-toggle="modal" data-target="#Add_" id="AddBtn" onclick="Add(0,'CorporateContact','Add','CorporateContacts');">Add New </a>
                    </div>
                </div>

                <table class="table table-striped table-bordered" id="CorporateContacts" data-show-fullscreen="true" data-show-columns="true" data-show-export="true" data-click-to-select="true" data-detail-formatter="detailFormatter">
                    <thead>
                        <tr>
                            <th data-field="SerialNo" data-sortable="true">Sr No.</th>
                            <th data-field="Name" data-sortable="true">Name</th>
                            <th data-field="CompanyName" data-sortable="true">CompanyName</th>
                            <th data-field="Designation" data-sortable="true">Designation</th>
                            <th data-field="Phone" data-sortable="true">Phone</th>
                            <th data-field="Email" data-sortable="true">Email</th>
                            <th data-field="operate" data-formatter="operateFormatter" events="operateEvents">Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>

</div>


<div class="modal fade in" id="Add_">
    <div id="AddModel_" class="modal-dialog PopUpChart" style="width:700px;"></div>
</div>

<script type="text/javascript">

        //$(document).ready(function () {
        //    dataTable("#CorporateContact");
        //    LoadDropDown();
        //});

        //function AddCorporateContact(id, name, action, controller) {
        //    Add(id, name, action, controller);
        //}

          $(document).ready(function () {
              ShowBootstrapTable("CorporateContacts", "GetAll", 1, 'CorporateContacts');
            LoadDropDown();
    });


    function operateFormatter(value, row, index) {
        if (row.Status == 1) {
            return [
                ' <a class="edit btn btn-mini" href="javascript:void(0);" data-toggle="modal" data-target="#Add_" title="Edit" onClick="Add(\'' + row.Id + '\',\'' + row.Name + '\',\'' + 'Edit' + '\',\'' + 'CorporateContacts' + '\',\'' + 'AddModel_' +'\')" >',
                '<i class="glyphicon glyphicon-edit"></i>',
                '</a>',

                '<a class="btn btn-mini" title = "Remove" href=@Url.Action("DeleteorRestore", "CorporateContacts")?Id=' + row.Id + '&Mode=' + 'Delete' + ' onclick="return confirm(\'' + 'Do you want to delete this record?' + '\')">',
                '<i class="fa fa-trash-o"></i>',
                '</a>'

            ].join('');
        }
        else
        {
            return [

                '<a class="btn btn-mini" title = "Restore" href=@Url.Action("DeleteorRestore", "CorporateContacts")?Id=' + row.Id + '&Mode=' + 'Restore' + ' onclick="return confirm(\'' + 'Do you want to restore this record?' + '\')">',
                '<i class="fa fa-refresh"></i>',
                '</a>'
            ].join('');
        }
    }
</script>