CP/Controllers/ItemsController.cs
using CP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EquiModels;
namespace CP.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        // GET: Items
        public ActionResult Index(string Search=null)
        {
            try
            {          
                return View();
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
           
        }

        public ActionResult UploaderItems(string Search = "Non-Banking")
        {
            try
            { 
                ViewBag.Uploaders = new SelectList(CompaniesRepository.GetUploaders(), "Code", "Name");
                UploaderItemsViewModel model = new UploaderItemsViewModel();
                model.Code = Search;
                return View(model);
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }
        [HttpGet]
        public JsonResult GetAllItems()
        {
            var data = ItemRepository.GetAll(null);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
       
        
    }
}

CP/Controllers/SectorsController.cs
using EquiModels;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CP.Models;


namespace CP.Controllers
{
    [Authorize]
    public class SectorsController : Controller
    {
        // GET: Sectors
        public ActionResult Index(string Status = "1")
        {
            try
            {             
                ViewBag.Search = Status;
                return View();
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        [HttpGet]
        public ActionResult Add()
        {
            try
            {
                TempData["Actionname"] = "Add";
                List<UserViewModel> AnalystList = UsersRepository.GetAnalysts();
                ViewBag.AnalystList = AnalystList.Select(x => new UserViewModel() { Id = x.Id, FullName = x.FullName }).ToList();
                ViewBag.SecondaryAnalystList = null;
                ViewBag.PrimaryAnalystList =new SelectList(AnalystList, "Id","FullName");
                ViewBag.SectorCompanies = null;
                ViewBag.Uploaders = new SelectList(CompaniesRepository.GetUploaders(), "Id", "Name");
                ViewBag.ReportCode = new SelectList(CompaniesRepository.GetReportCodes(), "Id", "Name");
                ViewBag.Errors = null;
                return PartialView();
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        [HttpPost]
        public ActionResult Add(SectorViewModel viewModel)
        {
            try
            {
                TempData["Actionname"] = "Add";
                ViewBag.GroupList = new SelectList(LovRepository.GetAll("SectorGroup"), "Value", "Label");
                List<UserViewModel> AnalystList = UsersRepository.GetAnalysts();
                ViewBag.AnalystList = AnalystList.Select(x => new UserViewModel() { Id = x.Id, FullName = x.FullName }).ToList(); 
                ViewBag.PrimaryAnalystList = new SelectList(AnalystList, "Id", "FullName");
                ViewBag.SecondaryAnalystList = (AnalystList).Where(x =>(viewModel.SecondaryAnalystIds != null && viewModel.SecondaryAnalystIds.Contains(x.Id))).ToList();
                ViewBag.Uploaders = new SelectList(CompaniesRepository.GetUploaders(), "Id", "Name");
                ViewBag.ReportCode = new SelectList(CompaniesRepository.GetReportCodes(), "Id", "Name");
                SectorsRepository.Add(viewModel,"Sectors/Add");
                if(CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView(viewModel);
                }
                else
                {
                    TempData["message"] = "Success";
                    return RedirectToAction("Add");
                }
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                var response = SectorsRepository.Get(Id);
                ViewBag.GroupList = new SelectList(LovRepository.GetAll("SectorGroup"), "Value", "Label");
                List<UserViewModel> AnalystList = UsersRepository.GetAnalysts();
                ViewBag.AnalystList = AnalystList.Select(x => new UserViewModel() {Id=x.Id,FullName=x.FullName }).ToList();
                ViewBag.PrimaryAnalystList = new SelectList(AnalystList, "Id", "FullName");
                ViewBag.SecondaryAnalystList = AnalystList.Where(x =>(response.SecondaryAnalystIds !=null && response.SecondaryAnalystIds.Contains(x.Id))).ToList();
                ViewBag.Uploaders = new SelectList(CompaniesRepository.GetUploaders(), "Id", "Name");
                ViewBag.ReportCode = new SelectList(CompaniesRepository.GetReportCodes(), "Id", "Name");
                return PartialView("Add", response);
            }
            catch(Exception e)
            {
                return View("Error", e);
            }
            
        }

        [HttpPost]
        public ActionResult Edit(SectorViewModel viewModel)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                ViewBag.GroupList = new SelectList(LovRepository.GetAll("SectorGroup"), "Value", "Label");
                List<UserViewModel> AnalystList = UsersRepository.GetAnalysts();
                ViewBag.AnalystList = AnalystList.Select(x => new UserViewModel() { Id = x.Id, FullName = x.FullName }).ToList();
                ViewBag.PrimaryAnalystList = new SelectList(AnalystList, "Id", "FullName");
                ViewBag.SecondaryAnalystList = (AnalystList).Where(x =>(viewModel.SecondaryAnalystIds != null && viewModel.SecondaryAnalystIds.Contains(x.Id)));
                ViewBag.Uploaders = new SelectList(CompaniesRepository.GetUploaders(), "Id", "Name");
                ViewBag.ReportCode = new SelectList(CompaniesRepository.GetReportCodes(), "Id", "Name");
                SectorsRepository.Add(viewModel, "Sectors/Edit");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView("Add", viewModel);
                }
                else
                {
                    TempData["message"] = "Success";
                    return RedirectToAction("Edit", new { Id = viewModel.Id });
                }
            }
            catch(Exception e)
            {
                return View("Error", e);
            }
           
        }

        public ActionResult DeleteOrRestore(int Id,string Mode)
        {
            try
            {
                string Path = null;
                if (Mode == "Delete")
                { Path = "Sectors/Delete"; }
                else Path = "Sectors/Restore";
                SectorsRepository.DeleteOrRestore(Id, Path);
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors= CommonRepository.ResponseErrors;
                }
                TempData["message"] = CommonRepository.StatusMessage;
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View("Error", e);
            }
          
    }
        [HttpGet]
        public JsonResult GetAll(string Status = "1", string SectorId = null)
        {
            var data = SectorsRepository.GetAll(Status);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

CP/Controllers/UploadLogController.cs
using CP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CP.Controllers
{
    [Authorize]
    public class UploadLogController : Controller
    {
        // GET: UploadLog
        public ActionResult Index()
        {
            try
            {               
                ViewBag.UploadLog  = UploadLogRepository.GetAll();
                ViewBag.FinYear = UploadLogRepository.Finyears();
                return View();

            }
            catch(Exception e)
            {
                return PartialView("Error", e);
            }
        }
    }
}

CP/Controllers/UsersController.cs
using CP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EquiModels;
using System.IO;
using System.Configuration;

namespace CP.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index(string Status = "1")
        {
            try
            { 
                ViewBag.Search = Status;
                return View();
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        public ActionResult Add()
        {
            try
            {
                TempData["Actionname"] = "Add";
                UserViewModel viewModel = new UserViewModel();
                ViewBag.RoleList = new SelectList(LovRepository.GetAll("Roles"), "Value", "Label");
                ViewBag.PrefixList = new SelectList(LovRepository.GetAll("Prefix"), "Value", "Label");
                ViewBag.Department = new SelectList(LovRepository.GetAll("Department"), "Value", "Label");
                ViewBag.Errors = null;
                viewModel.ImgPath = ConfigurationManager.AppSettings["ImgUrl"];
                return PartialView(viewModel);
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        [HttpPost]
        public ActionResult Add(UserViewModel viewModel,HttpPostedFileBase file=null)
        {
            try
            {
                TempData["actionname"] = "Add";
                ViewBag.RoleList = new SelectList(LovRepository.GetAll("Roles"), "Value", "Label");
                ViewBag.PrefixList = new SelectList(LovRepository.GetAll("Prefix"), "Value", "Label");
                ViewBag.Department = new SelectList(LovRepository.GetAll("Department"), "Value", "Label");
                viewModel.ImgPath = ConfigurationManager.AppSettings["ImgUrl"];

                if (file != null)
                {
                    viewModel.Avatar = UsersRepository.GetNextUserId("Users/NextUserId");
                }
                UsersRepository.Add(viewModel, "Users/Add");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView(viewModel);
                }
                else
                {
                    if (file != null)
                    {
                        string path = Path.Combine(Server.MapPath(viewModel.ImgPath), Path.GetFileName(viewModel.Avatar));
                        file.SaveAs(path);
                    }
                    TempData["message"] = "Success";
                    return RedirectToAction("Add");
                }

            }
            catch(Exception e)
            {
                return View("Error", e);
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                ViewBag.RoleList = new SelectList(LovRepository.GetAll("Roles"), "Value", "Label");
                ViewBag.PrefixList = new SelectList(LovRepository.GetAll("Prefix"), "Value", "Label");
                ViewBag.Department = new SelectList(LovRepository.GetAll("Department"), "Value", "Label");
                var response = UsersRepository.Get(Id);
                response.ImgPath = ConfigurationManager.AppSettings["ImgUrl"];

                return PartialView("Add", response);
            }
            catch (Exception e)
            {
                return View("Error", e);
            }
        }

        [HttpPost]
        public ActionResult Edit(UserViewModel viewModel,HttpPostedFileBase file)
        {
            try
            {
                TempData["Actionname"] = "Edit";
                ViewBag.RoleList = new SelectList(LovRepository.GetAll("Roles"), "Value", "Label");
                ViewBag.PrefixList = new SelectList(LovRepository.GetAll("Prefix"), "Value", "Label");
                ViewBag.Department = new SelectList(LovRepository.GetAll("Department"), "Value", "Label");
                viewModel.ImgPath = ConfigurationManager.AppSettings["ImgUrl"];
                if (file != null)
                {
                    viewModel.Avatar = "UserImage_" + viewModel.Id +".jpg";
                }
                UsersRepository.Add(viewModel, "Users/Edit");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView("Add", viewModel);
                }
                else
                {
                    if (file != null)
                    {
                        string path = Path.Combine(Server.MapPath(viewModel.ImgPath), Path.GetFileName(viewModel.Avatar));
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                        file.SaveAs(path);
                    }
                    TempData["message"] = "Success";
                    return RedirectToAction("Edit", new { Id = viewModel.Id });
                }
            }
            catch (Exception e)
            {
                return View("Error", e);
            }

        }
        [HttpGet]
        public ActionResult DeleteOrRestore(int Id, string Mode)
        {
            try
            {
                string Path = null;
                if (Mode == "Delete")
                { Path = "Users/Delete"; }
                else Path = "Users/Restore";
                UsersRepository.DeleteOrRestore(Id, Path);
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                }
                TempData["message"] = "Success";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error", e);
            }

        }
        [HttpGet]
         public JsonResult GetAll(string Status)
        {
            var data =  UsersRepository.GetAll(Status);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

CP/Views/Shared/NotAuthorize.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Not Autorized</title>
</head>
<body>
    <div>
        <h1>Authentication Failed</h1>
        <h2>You are not authorized.</h2>
    </div>
</body>
</html>

CP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Control Panel</title>
    <link rel="icon" href="~/Content/Images/centrum_icon.jpg" type="image/x-icon" sizes="16x16">
    @Styles.Render("~/Content/css")
    <link href="~/Content/intlTelInput.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
</head>
<body class="body">
    <div class="header">
        <div class="container">
            <div style="float: left;">
                <img src="@Url.Content("~/Content/Images/centrum_logo.jpg")" alt="" style="height: 36px; margin-top: 30px;" />
            </div>
            <div style="float: right; margin-top: 15px;">
                @{Html.RenderPartial("_LogOnUserControl");}
            </div>
            <br clear="all">
        </div>
    </div>
    <div class="subheader">
        @{Html.RenderPartial("_Menu");}
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <div id="footer">
        <p>
            Equity Monitor - Developed and maintained by Equitec &copy;
            @(DateTime.Now.Year - 1 + "-" + DateTime.Now.Year)(Version 2.1)
        </p>
    </div>
</body>
</html>

CP/Views/Shared/_LogOnUserControl.cshtml
<div style="float: right; margin-top: 15px;">
    <ul class="nav navbar-nav">
      
        @if(HttpContext.Current.Request.IsAuthenticated)
        {
           
        <li class="dropdown" style="margin-top: -10px;">
            @{ var UserSession = HttpContext.Current.Session["User"] as EquiModels.UserViewModel; }
            @if (UserSession != null)
            {
                <a href="#" style="color: black;"
                   class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">
                    Welcome <b class="users"> @(UserSession.FirstName + " " + UserSession.LastName)</b>
                    <br />

                </a>
            }

        </li>
         
            }

</ul>
</div>

CP/Views/Shared/_Menu.cshtml
<div class="container">
    <ul class="main">
        <li class="main" style="width:69px">
            <a href="@Url.Action("index", "home")" @(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "class=selected" : "")>
                <span class="glyphicon glyphicon-home" aria-hidden="true" style="color: gray;"></span> HOME
            </a>
        </li>
        @if (User.IsInRole("Administrator"))
        {
            <li class="dropdown main" style="margin-top: -10px;">
                <a href="#" class="dropdown-toggle"
                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="@Url.Content("~/Content/Images/masters.png")" alt="" width="15" height="15" />
                    MASTERS <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="@Url.Action("Index", "Sectors")" @((ViewContext.RouteData.Values["controller"].ToString() == "Sectors") ? "class=selected" : "")>
                            Sectors
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "Companies")" @(ViewContext.RouteData.Values["controller"].ToString() == "Sectors" ? "class=selected" : "")>
                            Companies
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "Clients")" @(ViewContext.RouteData.Values["controller"].ToString() == "Clients" ? "class=selected" : "")>
                            Clients
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "Users")" @(ViewContext.RouteData.Values["controller"].ToString() == "Sectors" ? "class=selected" : "")>
                            Users
                        </a>
                    </li>
                </ul>
            </li>

            <li class="dropdown main" style="margin-top: -10px;">
                <a href="#" class="dropdown-toggle"
                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="@Url.Content("~/Content/Images/AddressBook.png")" alt="" width="15" height="15" />
                    ADDRESS BOOK <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="@Url.Action("Index", "ClientContacts")" @((ViewContext.RouteData.Values["controller"].ToString() == "addressbook") ? "class=selected" : "")>
                            Client Contacts
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "CorporateContacts")" @(ViewContext.RouteData.Values["controller"].ToString() == "addressbook" ? "class=selected" : "")>
                            Corporate Contacts
                        </a>
                    </li>

                </ul>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("Index", "ResearchReports")">
                    <span aria-hidden="true" style="color: gray;"></span>  RESEARCH REPORTS
                </a>
            </li>
            <li class="dropdown main" style="margin-top: -10px;">
                <a href="#" class="dropdown-toggle"
                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="@Url.Content("~/Content/Images/cp.png")" alt="" width="16" height="16" />
                    RESEARCH CONTROL PANEL<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" style="margin-left: 4px;">
                    <li>
                        <a href="@Url.Action("Index", "Items")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Items
                        </a>
                    </li>


                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "UploaderItems")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Uploader Items
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "ReportItems")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Report Items
                        </a>
                    </li>
                </ul>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("index", "FormatGroup")">
                    <span aria-hidden="true" style="color: gray;"></span>  FORMAT GROUP
                </a>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("Index", "UploadLog")">
                    <span aria-hidden="true" style="color: gray;"></span>  UPLOAD LOG
                </a>
            </li>
        }
        @if (User.IsInRole("Analyst"))
        {
            <li class="dropdown main" style="margin-top: -10px;">
                <a href="#" class="dropdown-toggle"
                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="@Url.Content("~/Content/Images/AddressBook.png")" alt="" width="15" height="15" />
                    ADDRESS BOOK <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="@Url.Action("Index", "ClientContacts")" @((ViewContext.RouteData.Values["controller"].ToString() == "addressbook") ? "class=selected" : "")>
                            Client Contacts
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "CorporateContacts")" @(ViewContext.RouteData.Values["controller"].ToString() == "addressbook" ? "class=selected" : "")>
                            Corporate Contacts
                        </a>
                    </li>

                </ul>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("Index", "ResearchReports")">
                    <span aria-hidden="true" style="color: gray;"></span>  RESEARCH REPORTS
                </a>
            </li>
            <li class="dropdown main" style="margin-top: -10px;">
                <a href="#" class="dropdown-toggle"
                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="@Url.Content("~/Content/Images/cp.png")" alt="" width="16" height="16" />
                    RESEARCH CONTROL PANEL<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" style="margin-left: 4px;">
                    <li>
                        <a href="@Url.Action("Index", "Items")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Items
                        </a>
                    </li>


                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "UploaderItems")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Uploader Items
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index", "ReportItems")" @(ViewContext.RouteData.Values["controller"].ToString() == "researchcontrolpanel" ? "class=selected" : "")>
                            Report Items
                        </a>
                    </li>
                </ul>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("index", "FormatGroup")">
                    <span aria-hidden="true" style="color: gray;"></span>  FORMAT GROUP
                </a>
            </li>
            <li class="main" style="margin-top: -10px;">
                <a href="@Url.Action("Index", "UploadLog")">
                    <span aria-hidden="true" style="color: gray;"></span>  UPLOAD LOG
                </a>
            </li>
        }

    </ul>
</div>