CP/Controllers/ReportItemsController.cs
using CP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EquiModels;
namespace CP.Controllers
{
    [Authorize]
    public class ReportItemsController : Controller
    {
        // GET: ReportItems
        public ActionResult Index()
        {
            try
            {
                ViewBag.SectorGroup = CompaniesRepository.GetReportCodes();
                ViewBag.SectorReportItems = ReportItemsRepository.GetSectorReportItems();
                ViewBag.CompanieReportItems = ReportItemsRepository.GetCompanyReportItems();
                return View();
            }
            catch(Exception e)
            {
                return View("Error", e);
            }
        }
        [HttpGet]
        public ActionResult GetReportItems(string ReportGroup,string ReportCode,string ParentReportCode, string Category,string Entity)
        {
            try
            {
                ReportItemsViewModel model = new ReportItemsViewModel();
                var ReportCategory = ReportItemsRepository.GetReportItemsCategory(ReportCode); 
                model.Category =((Category == null)||(Category=="")) ? ReportCategory[0] : Category;
                model.ReportCode = ReportCode;
                model.ReportItems = ReportItemsRepository.GetReportItemsByCategory(model.Category, model.ReportCode);
                model.ReportType = model.ReportItems.Count > 0 ? model.ReportItems[0].ReportType : " ";
                ViewBag.Items = ItemRepository.GetAll(null).Select(x=>x.Code);
                ViewBag.FormatGroups = FormatGroupRepository.GetAll("1").Select(x=>x.FormatGroup);
                ViewBag.ItemTypes = LovRepository.GetAll("Item Type").Select(x=>x.Label);              
                ViewBag.ScaleList = LovRepository.GetAllScale().Select(x=>x.Scale);
                ViewBag.ReportCategory = ReportCategory;              
                model.ParentReportCode = ParentReportCode;
                model.ReportGroup = ReportGroup;
                return PartialView("GetReportItems", model);
            }
            catch(Exception e)
            {
                return PartialView("Error", e);
            }

        }
        [HttpPost]
        public ActionResult GetReportItems(ReportItemsViewModel model)
        {
            try
            {
                var ReportCategory = ReportItemsRepository.GetReportItemsCategory(model.ReportCode);
                model.ParentReportCode = model.ParentReportCode;
                ViewBag.ReportCategory = ReportCategory;
                ViewBag.Items = ItemRepository.GetAll(null).Select(x => x.Code);
                ViewBag.FormatGroups = FormatGroupRepository.GetAll("1").Select(x => x.FormatGroup);                 
                ReportItemsRepository.Add(model, "ReportItems/Save");
                if (CommonRepository.IsError)
                {
                    ViewBag.Errors = CommonRepository.ResponseErrors;
                    return PartialView(model);
                }
                else
                {
                    TempData["message"] = CommonRepository.StatusMessage;
                    return RedirectToAction("GetReportItems",model);
                }
            }
            catch (Exception e)
            {
                return PartialView("Error", e);
            }
        }

        public ActionResult AddSectorReportItems(ReportItemsViewModel model)
        {
            try
            {
                model.ReportCode = "SC_" + model.ReportItemType;
                model.ParentReportCode = model.ReportGroup;
                ReportItemsRepository.AddSecReportItems(model, "ReportItems/AddReportItems");
                return RedirectToAction("GetReportItems",model);
            }
            catch (Exception e)
            {
                return PartialView("Error", e);
            }
        }
        public ActionResult AddCompanyReportItems(ReportItemsViewModel model)
        {
            try
            {
                model.ReportCode = "CC_" + model.ReportItemType;
                model.ParentReportCode = model.ReportGroup;
                ReportItemsRepository.AddCmpReportItems(model, "ReportItems/AddReportItems");
                return RedirectToAction("GetReportItems", model);
            }
            catch (Exception e)
            {
                return PartialView("Error", e);
            }

        }

        [HttpGet]
        public ActionResult DeleteReportItems(string reportcode)
        {
            ReportItemsRepository.Delete(reportcode);
            TempData["message"] = "Report items deleted successfully.";
            return RedirectToAction("Index");
        }
      
    }
}

CP/Views/ReportItems/GetReportItems.cshtml
@model EquiModels.ReportItemsViewModel
@{

    string reportcode = "";

}



<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close btn-lg" onclick="javascript:location.reload()">
            &times;
        </button>
        <h4 class="modal-title" id="name">
            Report Items
        </h4>
    </div>
    @if (TempData["message"] != null && TempData["message"].ToString().Length > 0)
    {
        <div id="message">
            @TempData["message"]
        </div>
    }
    <div class="modal-body" style="height:500px; overflow-y:scroll;">
        <div>
            @using (Html.BeginForm("GetReportItems", "ReportItems", FormMethod.Post, new { @class = "form-Control", @onsubmit = "return OnFormSubmit(this);" }))
            {
                @Html.HiddenFor(x => x.ReportCode)
                @Html.HiddenFor(x => x.ReportType)
                @Html.HiddenFor(x => x.Category)
                @Html.HiddenFor(Model => Model.IsSectorItem)
                @Html.HiddenFor(Model => Model.ReportItemType)
                @Html.HiddenFor(x => x.ParentReportCode)

                <div id="reportgroup" style="float: left;width:174px;">
                    <table>
                        <tr>
                            <td>
                                &nbsp
                            </td>
                        </tr>
                        @if (ViewBag.ReportCategory != null)
                        {
                            foreach (var item in ViewBag.ReportCategory)
                            {
                                <tr>
                                    <td align="left">

                                        <a href="javascript:void(0);" @(item == Model.Category ? "class=selected" : "") onclick="ShowReportItems('@Model.ReportGroup','@Model.ReportCode','@Model.ParentReportCode','@Model.ReportItemType' ,'@item','GetReportItems','ReportItems');">@item</a>

                                    </td>
                                    <td>
                                        &nbsp
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
                <div class="row">
                    <div id="reportitems" class="form-group" style="float:right;width:950px;">

                        <table width="100%" class="popup_table">
                            <tr>
                                <th>
                                    Label
                                </th>
                                <th>
                                    Item Type
                                </th>
                                <th>
                                    Formula
                                </th>
                                <th>
                                    Sort Order
                                </th>
                                <th>
                                    Format
                                </th>
                                <th>
                                    Group
                                </th>
                                <th>
                                    Scale
                                </th>

                            </tr>

                            @if (Model.ReportItems != null)
                            {
                                for (int j = 0; j < Model.ReportItems.Count; j++)
                                {

                                    <tr>
                                        <td>
                                            @Html.TextBoxFor(x => x.ReportItems[j].Label, new { @class = "form-control" })
                                            @Html.HiddenFor(x => x.ReportItems[j].Category)
                                        </td>
                                        <td>
                                            @Html.DropDownListFor(x => x.ReportItems[j].Type, new SelectList(ViewBag.ItemTypes, Model.ReportItems[j].Type), new { @style = "width:100px;", @class = "form-control" })
                                        </td>
                                        <td class="form-group">
                                            @Html.DropDownListFor(x => x.ReportItems[j].ItemCode, new SelectList(ViewBag.Items, Model.ReportItems[j].ItemCode), "Select Formula", new { @class = "form-control demo-cs-multiselect", @style = "width:195px;" })
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(x => x.ReportItems[j].ItemSortOrder, new { @class = "form-control", @style = "width:84px;", onfocus = "setValue(this);", onchange = "swapValues(this)" })
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(x => x.ReportItems[j].Format, new { @class = "form-control" })
                                        </td>
                                        <td>
                                            @Html.DropDownListFor(x => x.ReportItems[j].FormatGroup, new SelectList(ViewBag.FormatGroups, Model.ReportItems[j].FormatGroup), new { @class = "form-control", @style = "width:95px;" })
                                        </td>
                                        <td>
                                            @Html.DropDownListFor(x => x.ReportItems[j].Scale, new SelectList(ViewBag.ScaleList, Model.ReportItems[j].Scale), "Select Scale", new { @class = "form-control", @style = "width:84px;" })
                                            @Html.HiddenFor(x => x.ReportItems[j].CategorySortOrder)
                                            @Html.HiddenFor(x => x.ReportItems[j].ReportType)
                                        </td>
                                    </tr>
                                }
                            }
                            <tr>
                                <td colspan="7" align="left">

                                    <input type="submit" value="Save" class="btn btn-info" id="save" />
                                    <input type="reset" value="Reset" class="btn btn-info" id="reset" />
                                    <input type="button" value="Close" data-dismiss="modal" onclick="javascript:location.reload()" class="btn btn-warning" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <br clear="all" />
            }
        </div>
    </div>
</div>
<script type="text/javascript">

    LoadDropDown();
   function OnFormSubmit(frm) {
        var res = '@TempData["message"]';
        SubmitForm(frm,res);
        return false;
    }


</script>

CP/Views/ReportItems/Index.cshtml
@{
    ViewBag.Title = "Report Items";
    int i = 1;
}


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <br />
                <h3 class="panel-title">Report Items</h3>
                <br />
            </div>
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered" style="margin-top: -13px;">
                    <thead>
                        <tr style="background: #f2f2f2;">
                            <th>
                                Sector Group
                            </th>
                            <th>
                                Sectors
                            </th>
                            <th>
                                Companies
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            <table>
                                @if (ViewBag.SectorGroup != null)
                                {
                                    foreach (var item in ViewBag.SectorGroup)
                                    {
                                        <tr>
                                            <td class="hasitems">
                                                @item.Name
                                            </td>
                                            <td>
                                                <a class="btn btn-mini" href="javascript:void(0);" onclick="ShowReportItems('','@item.Name','','','','GetReportItems','ReportItems');" title='Report Items [' @item.Name ']'>
                                                    <i class="glyphicon glyphicon-edit"></i>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }


                            </table>
                        </td>
                        <td>
                            <table>
                                @if (ViewBag.SectorReportItems != null)
                                {
                                    foreach (var Sec in ViewBag.SectorReportItems)
                                    {
                                        <tr>
                                            @if (Sec.SecCount > 0)
                                            {
                                                <td class="hasitems">
                                                    @(i + ". " + Sec.Name)
                                                </td>
                                                <td>

                                                    <a class="btn btn-mini" title='Report Items [@Sec.Name]' href="javascript:void(0);" onclick="ShowReportItems('@Sec.ReportGroup','@Sec.ReportCode','@Sec.ParentReportCode','@Sec.Name','','GetReportItems','ReportItems');">
                                                        <i class="glyphicon glyphicon-edit"></i>
                                                    </a>
                                                    <a class="btn btn-mini" title='Delete Report Items' href="@Url.Action("DeleteReportItems", new { reportcode = "SC_" + Sec.Name })" onclick="return confirm('Do you really want to delete report items?')"><i class="fa fa-trash-o"></i> </a>
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    @(i + ". " + Sec.Name)
                                                </td>
                                                <td>


                                                    <a class="btn btn-mini" title='Report Items [@Sec.Name]' href="javascript:void(0);" onclick="ShowReportItems('@Sec.ReportGroup','@Sec.ReportCode','','@Sec.Name','','AddSectorReportItems','ReportItems');">
                                                        <i class="glyphicon glyphicon-plus"></i>
                                                    </a>
                                                </td>
                                            }
                                        </tr>
                                        i++;
                                    }
                                }

                            </table>
                        </td>
                        <td>
                            <table>

                                @{i = 1;}
                                @if (ViewBag.CompanieReportItems != null)
                                {
                                    foreach (var Cmp in ViewBag.CompanieReportItems)
                                    {
                                        <tr>
                                            @if (Cmp.CmpCount > 0)
                                            {
                                                <td class="hasitems">
                                                    @(i + ". " + Cmp.Name)
                                                </td>
                                                <td>
                                                    @{string reportcode = "CC_" + Cmp.Code;}
                                                    <a class="btn btn-mini" title='Report Items [@Cmp.Name]' href="javascript:void(0);" onclick="ShowReportItems('@Cmp.ReportGroup','@Cmp.ReportCode','@Cmp.ParentReportCode','@Cmp.Code','','GetReportItems','ReportItems');">
                                                        <i class="glyphicon glyphicon-edit"></i>
                                                    </a>
                                                    <a class="btn btn-mini" href="@Url.Action("deletereportitems", new { reportcode = "CC_" + Cmp.Code })" title='Delete Report Items' onclick="return confirm('Do you really want to delete report items?')">
                                                        <i class="fa fa-trash-o"> </i>
                                                    </a>
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    @(i + ". " + Cmp.Name)
                                                </td>
                                                <td>
                                                    <a class="btn btn-mini" title='Report Items [@Cmp.Name]' href="javascript:void(0);" onclick="ShowReportItems('@Cmp.ReportGroup','@Cmp.ReportCode','','@Cmp.Code','','AddCompanyReportItems','ReportItems');">
                                                        <i class="glyphicon glyphicon-plus"></i>
                                                    </a>
                                                </td>
                                            }
                                        </tr>
                                        i++;
                                    }
                                }
                            </table>
                        </td>
                    </tr>
                </table>

            </div>
        </div>
    </div>
</div>
<div class="modal fade in" id="Add_">
    <div id="AddModel_" class="modal-dialog PopUpChart" style="width:1200px;">
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        LoadDropDown();
    });
</script>